/*
 * Composable Fabric Manager Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MemoryResourceBlockCompositionStatus struct {

	// The current state of the resource block from a composition perspective
	CompositionState string `json:"compositionState"`

	// The maximum number of compositions in which this resource block can participate simultaneously
	MaxCompositions int32 `json:"maxCompositions,omitempty"`

	// The number of compositions in which this resource block is currently participating
	NumberOfCompositions int32 `json:"numberOfCompositions,omitempty"`
}

// AssertMemoryResourceBlockCompositionStatusRequired checks if the required fields are not zero-ed
func AssertMemoryResourceBlockCompositionStatusRequired(obj MemoryResourceBlockCompositionStatus) error {
	elements := map[string]interface{}{
		"compositionState": obj.CompositionState,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMemoryResourceBlockCompositionStatusConstraints checks if the values respects the defined constraints
func AssertMemoryResourceBlockCompositionStatusConstraints(obj MemoryResourceBlockCompositionStatus) error {
	return nil
}
