/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

import (
	"context"
	"net/http"
)

// DefaultAPIRouter defines the required methods for binding the api requests to a responses for the DefaultAPI
// The DefaultAPIRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultAPIServicer to perform the required actions, then write the service results to the http response.
type DefaultAPIRouter interface {
	RedfishGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdMemoryDomainsGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdMemoryDomainsMemoryDomainIdGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdMemoryDomainsMemoryDomainIdMemoryChunksGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdMemoryDomainsMemoryDomainIdMemoryChunksMemoryChunksIdGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdPCIeDevicesGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdPCIeDevicesPCIeDeviceIdCXLLogicalDevicesCXLLogicalDeviceIdGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdPCIeDevicesPCIeDeviceIdCXLLogicalDevicesGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisChassisIdPCIeDevicesPCIeDeviceIdGet(http.ResponseWriter, *http.Request)
	RedfishV1ChassisGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdConnectionsConnectionIdDelete(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdConnectionsConnectionIdGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdConnectionsGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdConnectionsPost(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdEndpointsEndpointIdGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdEndpointsGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdSwitchesGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdSwitchesSwitchIdGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdSwitchesSwitchIdPortsGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsFabricIdSwitchesSwitchIdPortsPortIdGet(http.ResponseWriter, *http.Request)
	RedfishV1FabricsGet(http.ResponseWriter, *http.Request)
	RedfishV1Get(http.ResponseWriter, *http.Request)
	RedfishV1MetadataGet(http.ResponseWriter, *http.Request)
	RedfishV1OdataGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryDomainsGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksMemoryChunksIdDelete(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksMemoryChunksIdGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksPost(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsComputerSystemIdMemoryMemoryIdGet(http.ResponseWriter, *http.Request)
	RedfishV1SystemsGet(http.ResponseWriter, *http.Request)
}

// DefaultAPIServicer defines the api actions for the DefaultAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultAPIServicer interface {
	RedfishGet(context.Context) (ImplResponse, error)
	RedfishV1ChassisChassisIdGet(context.Context, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdMemoryDomainsGet(context.Context, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdMemoryDomainsMemoryDomainIdGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdMemoryDomainsMemoryDomainIdMemoryChunksGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdMemoryDomainsMemoryDomainIdMemoryChunksMemoryChunksIdGet(context.Context, string, string, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdPCIeDevicesGet(context.Context, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdPCIeDevicesPCIeDeviceIdCXLLogicalDevicesCXLLogicalDeviceIdGet(context.Context, string, string, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdPCIeDevicesPCIeDeviceIdCXLLogicalDevicesGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1ChassisChassisIdPCIeDevicesPCIeDeviceIdGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1ChassisGet(context.Context) (ImplResponse, error)
	RedfishV1FabricsFabricIdConnectionsConnectionIdDelete(context.Context, string, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdConnectionsConnectionIdGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdConnectionsGet(context.Context, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdConnectionsPost(context.Context, string, ConnectionV131Connection) (ImplResponse, error)
	RedfishV1FabricsFabricIdEndpointsEndpointIdGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdEndpointsGet(context.Context, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdGet(context.Context, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdSwitchesGet(context.Context, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdSwitchesSwitchIdGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdSwitchesSwitchIdPortsGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1FabricsFabricIdSwitchesSwitchIdPortsPortIdGet(context.Context, string, string, string) (ImplResponse, error)
	RedfishV1FabricsGet(context.Context) (ImplResponse, error)
	RedfishV1Get(context.Context) (ImplResponse, error)
	RedfishV1MetadataGet(context.Context) (ImplResponse, error)
	RedfishV1OdataGet(context.Context) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdGet(context.Context, string) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryDomainsGet(context.Context, string) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksMemoryChunksIdDelete(context.Context, string, string, string) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksMemoryChunksIdGet(context.Context, string, string, string) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryDomainsMemoryDomainIdMemoryChunksPost(context.Context, string, string, MemoryChunksV161MemoryChunks) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryGet(context.Context, string) (ImplResponse, error)
	RedfishV1SystemsComputerSystemIdMemoryMemoryIdGet(context.Context, string, string) (ImplResponse, error)
	RedfishV1SystemsGet(context.Context) (ImplResponse, error)
}
