/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ControlV150ControlMode string

// List of ControlV150ControlMode
const (
	CONTROLV150CONTROLMODE_AUTOMATIC ControlV150ControlMode = "Automatic"
	CONTROLV150CONTROLMODE_OVERRIDE  ControlV150ControlMode = "Override"
	CONTROLV150CONTROLMODE_MANUAL    ControlV150ControlMode = "Manual"
	CONTROLV150CONTROLMODE_DISABLED  ControlV150ControlMode = "Disabled"
)

// AssertControlV150ControlModeRequired checks if the required fields are not zero-ed
func AssertControlV150ControlModeRequired(obj ControlV150ControlMode) error {
	return nil
}

// AssertControlV150ControlModeConstraints checks if the values respects the defined constraints
func AssertControlV150ControlModeConstraints(obj ControlV150ControlMode) error {
	return nil
}
