/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type MemoryV1190BaseModuleType string

// List of MemoryV1190BaseModuleType
const (
	MEMORYV1190BASEMODULETYPE_RDIMM        MemoryV1190BaseModuleType = "RDIMM"
	MEMORYV1190BASEMODULETYPE_UDIMM        MemoryV1190BaseModuleType = "UDIMM"
	MEMORYV1190BASEMODULETYPE_SO_DIMM      MemoryV1190BaseModuleType = "SO_DIMM"
	MEMORYV1190BASEMODULETYPE_LRDIMM       MemoryV1190BaseModuleType = "LRDIMM"
	MEMORYV1190BASEMODULETYPE_MINI_RDIMM   MemoryV1190BaseModuleType = "Mini_RDIMM"
	MEMORYV1190BASEMODULETYPE_MINI_UDIMM   MemoryV1190BaseModuleType = "Mini_UDIMM"
	MEMORYV1190BASEMODULETYPE_SO_RDIMM_72B MemoryV1190BaseModuleType = "SO_RDIMM_72b"
	MEMORYV1190BASEMODULETYPE_SO_UDIMM_72B MemoryV1190BaseModuleType = "SO_UDIMM_72b"
	MEMORYV1190BASEMODULETYPE_SO_DIMM_16B  MemoryV1190BaseModuleType = "SO_DIMM_16b"
	MEMORYV1190BASEMODULETYPE_SO_DIMM_32B  MemoryV1190BaseModuleType = "SO_DIMM_32b"
	MEMORYV1190BASEMODULETYPE_DIE          MemoryV1190BaseModuleType = "Die"
)

// AssertMemoryV1190BaseModuleTypeRequired checks if the required fields are not zero-ed
func AssertMemoryV1190BaseModuleTypeRequired(obj MemoryV1190BaseModuleType) error {
	return nil
}

// AssertMemoryV1190BaseModuleTypeConstraints checks if the values respects the defined constraints
func AssertMemoryV1190BaseModuleTypeConstraints(obj MemoryV1190BaseModuleType) error {
	return nil
}
