/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ConnectionV131AccessCapability string

// List of ConnectionV131AccessCapability
const (
	CONNECTIONV131ACCESSCAPABILITY_READ  ConnectionV131AccessCapability = "Read"
	CONNECTIONV131ACCESSCAPABILITY_WRITE ConnectionV131AccessCapability = "Write"
)

// AssertConnectionV131AccessCapabilityRequired checks if the required fields are not zero-ed
func AssertConnectionV131AccessCapabilityRequired(obj ConnectionV131AccessCapability) error {
	return nil
}

// AssertConnectionV131AccessCapabilityConstraints checks if the values respects the defined constraints
func AssertConnectionV131AccessCapabilityConstraints(obj ConnectionV131AccessCapability) error {
	return nil
}
