/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// MemoryChunksV161Links - The links to other resources that are related to this resource.
type MemoryChunksV161Links struct {

	// An array of links to the CXL logical devices associated with this memory chunk.
	CXLLogicalDevices []OdataV4IdRef `json:"CXLLogicalDevices,omitempty"`

	// The number of items in a collection.
	CXLLogicalDevicesodataCount int64 `json:"CXLLogicalDevices@odata.count,omitempty"`

	// An array of links to the endpoints that connect to this memory chunk.
	Endpoints []OdataV4IdRef `json:"Endpoints,omitempty"`

	// The number of items in a collection.
	EndpointsodataCount int64 `json:"Endpoints@odata.count,omitempty"`

	// An array of links to the memory regions for which this memory chunk provides capacity.
	MemoryRegions []OdataV4IdRef `json:"MemoryRegions,omitempty"`

	// The number of items in a collection.
	MemoryRegionsodataCount int64 `json:"MemoryRegions@odata.count,omitempty"`

	// The OEM extension.
	Oem map[string]interface{} `json:"Oem,omitempty"`
}

// AssertMemoryChunksV161LinksRequired checks if the required fields are not zero-ed
func AssertMemoryChunksV161LinksRequired(obj MemoryChunksV161Links) error {
	for _, el := range obj.CXLLogicalDevices {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.Endpoints {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.MemoryRegions {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMemoryChunksV161LinksConstraints checks if the values respects the defined constraints
func AssertMemoryChunksV161LinksConstraints(obj MemoryChunksV161Links) error {
	return nil
}
