/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type CxlLogicalDeviceV111CxlSemantic string

// List of CxlLogicalDeviceV111CxlSemantic
const (
	CXLLOGICALDEVICEV111CXLSEMANTIC_CX_LIO    CxlLogicalDeviceV111CxlSemantic = "CXLio"
	CXLLOGICALDEVICEV111CXLSEMANTIC_CX_LCACHE CxlLogicalDeviceV111CxlSemantic = "CXLcache"
	CXLLOGICALDEVICEV111CXLSEMANTIC_CX_LMEM   CxlLogicalDeviceV111CxlSemantic = "CXLmem"
)

// AssertCxlLogicalDeviceV111CxlSemanticRequired checks if the required fields are not zero-ed
func AssertCxlLogicalDeviceV111CxlSemanticRequired(obj CxlLogicalDeviceV111CxlSemantic) error {
	return nil
}

// AssertCxlLogicalDeviceV111CxlSemanticConstraints checks if the values respects the defined constraints
func AssertCxlLogicalDeviceV111CxlSemanticConstraints(obj CxlLogicalDeviceV111CxlSemantic) error {
	return nil
}
