/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ResourceV1190ContactInfo - Contact information for this resource.
type ResourceV1190ContactInfo struct {

	// Name of this contact.
	ContactName *string `json:"ContactName,omitempty"`

	// Email address for this contact.
	EmailAddress *string `json:"EmailAddress,omitempty"`

	// Phone number for this contact.
	PhoneNumber *string `json:"PhoneNumber,omitempty"`
}

// AssertResourceV1190ContactInfoRequired checks if the required fields are not zero-ed
func AssertResourceV1190ContactInfoRequired(obj ResourceV1190ContactInfo) error {
	return nil
}

// AssertResourceV1190ContactInfoConstraints checks if the values respects the defined constraints
func AssertResourceV1190ContactInfoConstraints(obj ResourceV1190ContactInfo) error {
	return nil
}
