/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ComputerSystemV1220KeyManagement - The key management settings of a computer system.
type ComputerSystemV1220KeyManagement struct {
	KMIPCertificates OdataV4IdRef `json:"KMIPCertificates,omitempty"`

	// The KMIP servers to which this computer system is subscribed.
	KMIPServers []ComputerSystemV1220KmipServer `json:"KMIPServers,omitempty"`
}

// AssertComputerSystemV1220KeyManagementRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220KeyManagementRequired(obj ComputerSystemV1220KeyManagement) error {
	if err := AssertOdataV4IdRefRequired(obj.KMIPCertificates); err != nil {
		return err
	}
	for _, el := range obj.KMIPServers {
		if err := AssertComputerSystemV1220KmipServerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertComputerSystemV1220KeyManagementConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220KeyManagementConstraints(obj ComputerSystemV1220KeyManagement) error {
	return nil
}
