/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ComputerSystemV1220WatchdogTimeoutActions : The enumerations of WatchdogTimeoutActions specify the choice of action to take when the host watchdog timer reaches its timeout value.
type ComputerSystemV1220WatchdogTimeoutActions string

// List of ComputerSystemV1220WatchdogTimeoutActions
const (
	COMPUTERSYSTEMV1220WATCHDOGTIMEOUTACTIONS_NONE         ComputerSystemV1220WatchdogTimeoutActions = "None"
	COMPUTERSYSTEMV1220WATCHDOGTIMEOUTACTIONS_RESET_SYSTEM ComputerSystemV1220WatchdogTimeoutActions = "ResetSystem"
	COMPUTERSYSTEMV1220WATCHDOGTIMEOUTACTIONS_POWER_CYCLE  ComputerSystemV1220WatchdogTimeoutActions = "PowerCycle"
	COMPUTERSYSTEMV1220WATCHDOGTIMEOUTACTIONS_POWER_DOWN   ComputerSystemV1220WatchdogTimeoutActions = "PowerDown"
	COMPUTERSYSTEMV1220WATCHDOGTIMEOUTACTIONS_OEM          ComputerSystemV1220WatchdogTimeoutActions = "OEM"
)

// AssertComputerSystemV1220WatchdogTimeoutActionsRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220WatchdogTimeoutActionsRequired(obj ComputerSystemV1220WatchdogTimeoutActions) error {
	return nil
}

// AssertComputerSystemV1220WatchdogTimeoutActionsConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220WatchdogTimeoutActionsConstraints(obj ComputerSystemV1220WatchdogTimeoutActions) error {
	return nil
}
