/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ComputerSystemV1220AutomaticRetryConfig string

// List of ComputerSystemV1220AutomaticRetryConfig
const (
	COMPUTERSYSTEMV1220AUTOMATICRETRYCONFIG_DISABLED       ComputerSystemV1220AutomaticRetryConfig = "Disabled"
	COMPUTERSYSTEMV1220AUTOMATICRETRYCONFIG_RETRY_ATTEMPTS ComputerSystemV1220AutomaticRetryConfig = "RetryAttempts"
	COMPUTERSYSTEMV1220AUTOMATICRETRYCONFIG_RETRY_ALWAYS   ComputerSystemV1220AutomaticRetryConfig = "RetryAlways"
)

// AssertComputerSystemV1220AutomaticRetryConfigRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220AutomaticRetryConfigRequired(obj ComputerSystemV1220AutomaticRetryConfig) error {
	return nil
}

// AssertComputerSystemV1220AutomaticRetryConfigConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220AutomaticRetryConfigConstraints(obj ComputerSystemV1220AutomaticRetryConfig) error {
	return nil
}
