/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// IpAddressesIpv4Address - This type describes an IPv4 address.
type IpAddressesIpv4Address struct {

	// The IPv4 address.
	Address *string `json:"Address,omitempty"`

	AddressOrigin IpAddressesV114Ipv4AddressOrigin `json:"AddressOrigin,omitempty"`

	// The IPv4 gateway for this address.
	Gateway *string `json:"Gateway,omitempty"`

	// The OEM extension.
	Oem map[string]interface{} `json:"Oem,omitempty"`

	SubnetMask string `json:"SubnetMask,omitempty"`
}

// AssertIpAddressesIpv4AddressRequired checks if the required fields are not zero-ed
func AssertIpAddressesIpv4AddressRequired(obj IpAddressesIpv4Address) error {
	return nil
}

// AssertIpAddressesIpv4AddressConstraints checks if the values respects the defined constraints
func AssertIpAddressesIpv4AddressConstraints(obj IpAddressesIpv4Address) error {
	return nil
}
