/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ComputerSystemBootSource string

// List of ComputerSystemBootSource
const (
	COMPUTERSYSTEMBOOTSOURCE_NONE           ComputerSystemBootSource = "None"
	COMPUTERSYSTEMBOOTSOURCE_PXE            ComputerSystemBootSource = "Pxe"
	COMPUTERSYSTEMBOOTSOURCE_FLOPPY         ComputerSystemBootSource = "Floppy"
	COMPUTERSYSTEMBOOTSOURCE_CD             ComputerSystemBootSource = "Cd"
	COMPUTERSYSTEMBOOTSOURCE_USB            ComputerSystemBootSource = "Usb"
	COMPUTERSYSTEMBOOTSOURCE_HDD            ComputerSystemBootSource = "Hdd"
	COMPUTERSYSTEMBOOTSOURCE_BIOS_SETUP     ComputerSystemBootSource = "BiosSetup"
	COMPUTERSYSTEMBOOTSOURCE_UTILITIES      ComputerSystemBootSource = "Utilities"
	COMPUTERSYSTEMBOOTSOURCE_DIAGS          ComputerSystemBootSource = "Diags"
	COMPUTERSYSTEMBOOTSOURCE_UEFI_SHELL     ComputerSystemBootSource = "UefiShell"
	COMPUTERSYSTEMBOOTSOURCE_UEFI_TARGET    ComputerSystemBootSource = "UefiTarget"
	COMPUTERSYSTEMBOOTSOURCE_SD_CARD        ComputerSystemBootSource = "SDCard"
	COMPUTERSYSTEMBOOTSOURCE_UEFI_HTTP      ComputerSystemBootSource = "UefiHttp"
	COMPUTERSYSTEMBOOTSOURCE_REMOTE_DRIVE   ComputerSystemBootSource = "RemoteDrive"
	COMPUTERSYSTEMBOOTSOURCE_UEFI_BOOT_NEXT ComputerSystemBootSource = "UefiBootNext"
	COMPUTERSYSTEMBOOTSOURCE_RECOVERY       ComputerSystemBootSource = "Recovery"
)

// AssertComputerSystemBootSourceRequired checks if the required fields are not zero-ed
func AssertComputerSystemBootSourceRequired(obj ComputerSystemBootSource) error {
	return nil
}

// AssertComputerSystemBootSourceConstraints checks if the values respects the defined constraints
func AssertComputerSystemBootSourceConstraints(obj ComputerSystemBootSource) error {
	return nil
}
