/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ConnectionV131ChapConnectionKey - The CHAP-specific permission key information for a connection.
type ConnectionV131ChapConnectionKey struct {

	// The password for CHAP authentication.  The value is `null` in responses.
	CHAPPassword *string `json:"CHAPPassword,omitempty"`

	// The username for CHAP authentication.
	CHAPUsername *string `json:"CHAPUsername,omitempty"`

	// The initiator shared secret for mutual (2-way) CHAP authentication.  The value is `null` in responses.
	InitiatorCHAPPassword *string `json:"InitiatorCHAPPassword,omitempty"`

	// The initiator username for mutual (2-way) CHAP authentication.
	InitiatorCHAPUsername *string `json:"InitiatorCHAPUsername,omitempty"`

	// The target shared secret for mutual (2-way) CHAP authentication.  The value is `null` in responses.
	TargetCHAPPassword *string `json:"TargetCHAPPassword,omitempty"`
}

// AssertConnectionV131ChapConnectionKeyRequired checks if the required fields are not zero-ed
func AssertConnectionV131ChapConnectionKeyRequired(obj ConnectionV131ChapConnectionKey) error {
	return nil
}

// AssertConnectionV131ChapConnectionKeyConstraints checks if the values respects the defined constraints
func AssertConnectionV131ChapConnectionKeyConstraints(obj ConnectionV131ChapConnectionKey) error {
	return nil
}
