/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type MemoryChunksV161MediaLocation string

// List of MemoryChunksV161MediaLocation
const (
	MEMORYCHUNKSV161MEDIALOCATION_LOCAL  MemoryChunksV161MediaLocation = "Local"
	MEMORYCHUNKSV161MEDIALOCATION_REMOTE MemoryChunksV161MediaLocation = "Remote"
	MEMORYCHUNKSV161MEDIALOCATION_MIXED  MemoryChunksV161MediaLocation = "Mixed"
)

// AssertMemoryChunksV161MediaLocationRequired checks if the required fields are not zero-ed
func AssertMemoryChunksV161MediaLocationRequired(obj MemoryChunksV161MediaLocation) error {
	return nil
}

// AssertMemoryChunksV161MediaLocationConstraints checks if the values respects the defined constraints
func AssertMemoryChunksV161MediaLocationConstraints(obj MemoryChunksV161MediaLocation) error {
	return nil
}
