/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ConnectionV131ConnectionType string

// List of ConnectionV131ConnectionType
const (
	CONNECTIONV131CONNECTIONTYPE_STORAGE ConnectionV131ConnectionType = "Storage"
	CONNECTIONV131CONNECTIONTYPE_MEMORY  ConnectionV131ConnectionType = "Memory"
)

// AssertConnectionV131ConnectionTypeRequired checks if the required fields are not zero-ed
func AssertConnectionV131ConnectionTypeRequired(obj ConnectionV131ConnectionType) error {
	return nil
}

// AssertConnectionV131ConnectionTypeConstraints checks if the values respects the defined constraints
func AssertConnectionV131ConnectionTypeConstraints(obj ConnectionV131ConnectionType) error {
	return nil
}
