/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type PortV1110ConnectedDeviceType string

// List of PortV1110ConnectedDeviceType
const (
	PORTV1110CONNECTEDDEVICETYPE_NONE        PortV1110ConnectedDeviceType = "None"
	PORTV1110CONNECTEDDEVICETYPE_PCIE_DEVICE PortV1110ConnectedDeviceType = "PCIeDevice"
	PORTV1110CONNECTEDDEVICETYPE_TYPE1       PortV1110ConnectedDeviceType = "Type1"
	PORTV1110CONNECTEDDEVICETYPE_TYPE2       PortV1110ConnectedDeviceType = "Type2"
	PORTV1110CONNECTEDDEVICETYPE_TYPE3_SLD   PortV1110ConnectedDeviceType = "Type3SLD"
	PORTV1110CONNECTEDDEVICETYPE_TYPE3_MLD   PortV1110ConnectedDeviceType = "Type3MLD"
)

// AssertPortV1110ConnectedDeviceTypeRequired checks if the required fields are not zero-ed
func AssertPortV1110ConnectedDeviceTypeRequired(obj PortV1110ConnectedDeviceType) error {
	return nil
}

// AssertPortV1110ConnectedDeviceTypeConstraints checks if the values respects the defined constraints
func AssertPortV1110ConnectedDeviceTypeConstraints(obj PortV1110ConnectedDeviceType) error {
	return nil
}
