/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

import (
	"errors"
)

// StorageV1160CacheSummary - This type describes the cache memory of the storage controller in general detail.
type StorageV1160CacheSummary struct {

	// The portion of the cache memory that is persistent, measured in MiB.
	PersistentCacheSizeMiB *int64 `json:"PersistentCacheSizeMiB,omitempty"`

	Status ResourceStatus `json:"Status,omitempty"`

	// The total configured cache memory, measured in MiB.
	TotalCacheSizeMiB *int64 `json:"TotalCacheSizeMiB"`
}

// AssertStorageV1160CacheSummaryRequired checks if the required fields are not zero-ed
func AssertStorageV1160CacheSummaryRequired(obj StorageV1160CacheSummary) error {
	elements := map[string]interface{}{
		"TotalCacheSizeMiB": obj.TotalCacheSizeMiB,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertResourceStatusRequired(obj.Status); err != nil {
		return err
	}
	return nil
}

// AssertStorageV1160CacheSummaryConstraints checks if the values respects the defined constraints
func AssertStorageV1160CacheSummaryConstraints(obj StorageV1160CacheSummary) error {
	if obj.PersistentCacheSizeMiB != nil && *obj.PersistentCacheSizeMiB < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	if obj.TotalCacheSizeMiB != nil && *obj.TotalCacheSizeMiB < 0 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
