/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ConnectionV131GenZConnectionKey - The Gen-Z-specific permission key information for a connection.
type ConnectionV131GenZConnectionKey struct {

	// The Access Key for this connection.
	AccessKey string `json:"AccessKey,omitempty"`

	// Indicates whether Region Key domain checking is enabled for this connection.
	RKeyDomainCheckingEnabled bool `json:"RKeyDomainCheckingEnabled,omitempty"`

	// The read-only Region Key for this connection.
	RKeyReadOnlyKey string `json:"RKeyReadOnlyKey,omitempty"`

	// The read-write Region Key for this connection.
	RKeyReadWriteKey string `json:"RKeyReadWriteKey,omitempty"`
}

// AssertConnectionV131GenZConnectionKeyRequired checks if the required fields are not zero-ed
func AssertConnectionV131GenZConnectionKeyRequired(obj ConnectionV131GenZConnectionKey) error {
	return nil
}

// AssertConnectionV131GenZConnectionKeyConstraints checks if the values respects the defined constraints
func AssertConnectionV131GenZConnectionKeyConstraints(obj ConnectionV131GenZConnectionKey) error {
	return nil
}
