/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ConnectionV131VolumeInfo - The combination of permissions and volume information.
type ConnectionV131VolumeInfo struct {

	// Supported I/O access capabilities.
	AccessCapabilities []ConnectionV131AccessCapability `json:"AccessCapabilities,omitempty"`

	AccessState ConnectionV131AccessState `json:"AccessState,omitempty"`

	// The initiator-visible logical unit number (LUN) assigned to this volume.
	LUN *int64 `json:"LUN,omitempty"`

	Volume OdataV4IdRef `json:"Volume,omitempty"`
}

// AssertConnectionV131VolumeInfoRequired checks if the required fields are not zero-ed
func AssertConnectionV131VolumeInfoRequired(obj ConnectionV131VolumeInfo) error {
	if err := AssertOdataV4IdRefRequired(obj.Volume); err != nil {
		return err
	}
	return nil
}

// AssertConnectionV131VolumeInfoConstraints checks if the values respects the defined constraints
func AssertConnectionV131VolumeInfoConstraints(obj ConnectionV131VolumeInfo) error {
	return nil
}
