/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ResourceIdentifier - Any additional identifiers for a resource.
type ResourceIdentifier struct {

	// The world-wide, persistent name of the resource.
	DurableName *string `json:"DurableName,omitempty"`

	DurableNameFormat ResourceV1180DurableNameFormat `json:"DurableNameFormat,omitempty"`
}

// AssertResourceIdentifierRequired checks if the required fields are not zero-ed
func AssertResourceIdentifierRequired(obj ResourceIdentifier) error {
	return nil
}

// AssertResourceIdentifierConstraints checks if the values respects the defined constraints
func AssertResourceIdentifierConstraints(obj ResourceIdentifier) error {
	return nil
}
