/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// EndpointV181Gcid - The Global Component ID (GCID).
type EndpointV181Gcid struct {

	// The component identifier portion of the GCID for the entity.
	CID *string `json:"CID,omitempty"`

	// The subnet identifier portion of the GCID for the entity.
	SID *string `json:"SID,omitempty"`
}

// AssertEndpointV181GcidRequired checks if the required fields are not zero-ed
func AssertEndpointV181GcidRequired(obj EndpointV181Gcid) error {
	return nil
}

// AssertEndpointV181GcidConstraints checks if the values respects the defined constraints
func AssertEndpointV181GcidConstraints(obj EndpointV181Gcid) error {
	return nil
}
