/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type IpAddressesV114Ipv6AddressOrigin string

// List of IpAddressesV114Ipv6AddressOrigin
const (
	IPADDRESSESV114IPV6ADDRESSORIGIN_STATIC     IpAddressesV114Ipv6AddressOrigin = "Static"
	IPADDRESSESV114IPV6ADDRESSORIGIN_DHCPV6     IpAddressesV114Ipv6AddressOrigin = "DHCPv6"
	IPADDRESSESV114IPV6ADDRESSORIGIN_LINK_LOCAL IpAddressesV114Ipv6AddressOrigin = "LinkLocal"
	IPADDRESSESV114IPV6ADDRESSORIGIN_SLAAC      IpAddressesV114Ipv6AddressOrigin = "SLAAC"
)

// AssertIpAddressesV114Ipv6AddressOriginRequired checks if the required fields are not zero-ed
func AssertIpAddressesV114Ipv6AddressOriginRequired(obj IpAddressesV114Ipv6AddressOrigin) error {
	return nil
}

// AssertIpAddressesV114Ipv6AddressOriginConstraints checks if the values respects the defined constraints
func AssertIpAddressesV114Ipv6AddressOriginConstraints(obj IpAddressesV114Ipv6AddressOrigin) error {
	return nil
}
