/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ManagerAccountAccountTypes string

// List of ManagerAccountAccountTypes
const (
	MANAGERACCOUNTACCOUNTTYPES_REDFISH         ManagerAccountAccountTypes = "Redfish"
	MANAGERACCOUNTACCOUNTTYPES_SNMP            ManagerAccountAccountTypes = "SNMP"
	MANAGERACCOUNTACCOUNTTYPES_OEM             ManagerAccountAccountTypes = "OEM"
	MANAGERACCOUNTACCOUNTTYPES_HOST_CONSOLE    ManagerAccountAccountTypes = "HostConsole"
	MANAGERACCOUNTACCOUNTTYPES_MANAGER_CONSOLE ManagerAccountAccountTypes = "ManagerConsole"
	MANAGERACCOUNTACCOUNTTYPES_IPMI            ManagerAccountAccountTypes = "IPMI"
	MANAGERACCOUNTACCOUNTTYPES_KVMIP           ManagerAccountAccountTypes = "KVMIP"
	MANAGERACCOUNTACCOUNTTYPES_VIRTUAL_MEDIA   ManagerAccountAccountTypes = "VirtualMedia"
	MANAGERACCOUNTACCOUNTTYPES_WEB_UI          ManagerAccountAccountTypes = "WebUI"
)

// AssertManagerAccountAccountTypesRequired checks if the required fields are not zero-ed
func AssertManagerAccountAccountTypesRequired(obj ManagerAccountAccountTypes) error {
	return nil
}

// AssertManagerAccountAccountTypesConstraints checks if the values respects the defined constraints
func AssertManagerAccountAccountTypesConstraints(obj ManagerAccountAccountTypes) error {
	return nil
}
