/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type StorageStorageControllerSupportedRaidTypesInner struct {
}

// AssertStorageStorageControllerSupportedRaidTypesInnerRequired checks if the required fields are not zero-ed
func AssertStorageStorageControllerSupportedRaidTypesInnerRequired(obj StorageStorageControllerSupportedRaidTypesInner) error {
	return nil
}

// AssertStorageStorageControllerSupportedRaidTypesInnerConstraints checks if the values respects the defined constraints
func AssertStorageStorageControllerSupportedRaidTypesInnerConstraints(obj StorageStorageControllerSupportedRaidTypesInner) error {
	return nil
}
