/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// MemoryChunksV161Actions - The available actions for this resource.
type MemoryChunksV161Actions struct {

	// The available OEM-specific actions for this resource.
	Oem map[string]interface{} `json:"Oem,omitempty"`
}

// AssertMemoryChunksV161ActionsRequired checks if the required fields are not zero-ed
func AssertMemoryChunksV161ActionsRequired(obj MemoryChunksV161Actions) error {
	return nil
}

// AssertMemoryChunksV161ActionsConstraints checks if the values respects the defined constraints
func AssertMemoryChunksV161ActionsConstraints(obj MemoryChunksV161Actions) error {
	return nil
}
