/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ResourceV1180PhysicalAddress - The physical address for a resource.
type ResourceV1180PhysicalAddress struct {

	// City, township, or shi (JP).
	City *string `json:"City,omitempty"`

	// The country.
	Country *string `json:"Country,omitempty"`

	// The ISO 3166-1 country code.
	ISOCountryCode *string `json:"ISOCountryCode,omitempty"`

	// ISO 3166-2 subdivision code.
	ISOSubdivisionCode *string `json:"ISOSubdivisionCode,omitempty"`

	// The postal code.
	PostalCode *string `json:"PostalCode,omitempty"`

	// State or province.
	StateOrProvince *string `json:"StateOrProvince,omitempty"`

	// The street-level address, including building, room, or other identifiers.
	StreetAddress *string `json:"StreetAddress,omitempty"`
}

// AssertResourceV1180PhysicalAddressRequired checks if the required fields are not zero-ed
func AssertResourceV1180PhysicalAddressRequired(obj ResourceV1180PhysicalAddress) error {
	return nil
}

// AssertResourceV1180PhysicalAddressConstraints checks if the values respects the defined constraints
func AssertResourceV1180PhysicalAddressConstraints(obj ResourceV1180PhysicalAddress) error {
	return nil
}
