/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type AccountServiceV1150LocalAccountAuth string

// List of AccountServiceV1150LocalAccountAuth
const (
	ACCOUNTSERVICEV1150LOCALACCOUNTAUTH_ENABLED     AccountServiceV1150LocalAccountAuth = "Enabled"
	ACCOUNTSERVICEV1150LOCALACCOUNTAUTH_DISABLED    AccountServiceV1150LocalAccountAuth = "Disabled"
	ACCOUNTSERVICEV1150LOCALACCOUNTAUTH_FALLBACK    AccountServiceV1150LocalAccountAuth = "Fallback"
	ACCOUNTSERVICEV1150LOCALACCOUNTAUTH_LOCAL_FIRST AccountServiceV1150LocalAccountAuth = "LocalFirst"
)

// AssertAccountServiceV1150LocalAccountAuthRequired checks if the required fields are not zero-ed
func AssertAccountServiceV1150LocalAccountAuthRequired(obj AccountServiceV1150LocalAccountAuth) error {
	return nil
}

// AssertAccountServiceV1150LocalAccountAuthConstraints checks if the values respects the defined constraints
func AssertAccountServiceV1150LocalAccountAuthConstraints(obj AccountServiceV1150LocalAccountAuth) error {
	return nil
}
