/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// StorageV1160StorageControllerLinks - The links to other resources that are related to this resource.
type StorageV1160StorageControllerLinks struct {

	// An array of links to the endpoints that connect to this controller.
	Endpoints []OdataV4IdRef `json:"Endpoints,omitempty"`

	// The number of items in a collection.
	EndpointsodataCount int64 `json:"Endpoints@odata.count,omitempty"`

	// The OEM extension.
	Oem map[string]interface{} `json:"Oem,omitempty"`

	// An array of links to the PCIe functions that the storage controller produces.
	PCIeFunctions []OdataV4IdRef `json:"PCIeFunctions,omitempty"`

	// The number of items in a collection.
	PCIeFunctionsodataCount int64 `json:"PCIeFunctions@odata.count,omitempty"`

	// An array of links to the storage services that connect to this controller.
	// Deprecated
	StorageServices []OdataV4IdRef `json:"StorageServices,omitempty"`

	// The number of items in a collection.
	StorageServicesodataCount int64 `json:"StorageServices@odata.count,omitempty"`
}

// AssertStorageV1160StorageControllerLinksRequired checks if the required fields are not zero-ed
func AssertStorageV1160StorageControllerLinksRequired(obj StorageV1160StorageControllerLinks) error {
	for _, el := range obj.Endpoints {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.PCIeFunctions {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.StorageServices {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertStorageV1160StorageControllerLinksConstraints checks if the values respects the defined constraints
func AssertStorageV1160StorageControllerLinksConstraints(obj StorageV1160StorageControllerLinks) error {
	return nil
}
