/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ResolutionStepV100ResolutionType string

// List of ResolutionStepV100ResolutionType
const (
	RESOLUTIONSTEPV100RESOLUTIONTYPE_CONTACT_VENDOR          ResolutionStepV100ResolutionType = "ContactVendor"
	RESOLUTIONSTEPV100RESOLUTIONTYPE_REPLACE_COMPONENT       ResolutionStepV100ResolutionType = "ReplaceComponent"
	RESOLUTIONSTEPV100RESOLUTIONTYPE_FIRMWARE_UPDATE         ResolutionStepV100ResolutionType = "FirmwareUpdate"
	RESOLUTIONSTEPV100RESOLUTIONTYPE_RESET                   ResolutionStepV100ResolutionType = "Reset"
	RESOLUTIONSTEPV100RESOLUTIONTYPE_POWER_CYCLE             ResolutionStepV100ResolutionType = "PowerCycle"
	RESOLUTIONSTEPV100RESOLUTIONTYPE_RESET_TO_DEFAULTS       ResolutionStepV100ResolutionType = "ResetToDefaults"
	RESOLUTIONSTEPV100RESOLUTIONTYPE_COLLECT_DIAGNOSTIC_DATA ResolutionStepV100ResolutionType = "CollectDiagnosticData"
	RESOLUTIONSTEPV100RESOLUTIONTYPE_OEM                     ResolutionStepV100ResolutionType = "OEM"
)

// AssertResolutionStepV100ResolutionTypeRequired checks if the required fields are not zero-ed
func AssertResolutionStepV100ResolutionTypeRequired(obj ResolutionStepV100ResolutionType) error {
	return nil
}

// AssertResolutionStepV100ResolutionTypeConstraints checks if the values respects the defined constraints
func AssertResolutionStepV100ResolutionTypeConstraints(obj ResolutionStepV100ResolutionType) error {
	return nil
}
