/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type PortV1110FlowControl string

// List of PortV1110FlowControl
const (
	PORTV1110FLOWCONTROL_NONE  PortV1110FlowControl = "None"
	PORTV1110FLOWCONTROL_TX    PortV1110FlowControl = "TX"
	PORTV1110FLOWCONTROL_RX    PortV1110FlowControl = "RX"
	PORTV1110FLOWCONTROL_TX_RX PortV1110FlowControl = "TX_RX"
)

// AssertPortV1110FlowControlRequired checks if the required fields are not zero-ed
func AssertPortV1110FlowControlRequired(obj PortV1110FlowControl) error {
	return nil
}

// AssertPortV1110FlowControlConstraints checks if the values respects the defined constraints
func AssertPortV1110FlowControlConstraints(obj PortV1110FlowControl) error {
	return nil
}
