/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// FabricV131Links - The links to other resources that are related to this resource.
type FabricV131Links struct {

	// The OEM extension.
	Oem map[string]interface{} `json:"Oem,omitempty"`
}

// AssertFabricV131LinksRequired checks if the required fields are not zero-ed
func AssertFabricV131LinksRequired(obj FabricV131Links) error {
	return nil
}

// AssertFabricV131LinksConstraints checks if the values respects the defined constraints
func AssertFabricV131LinksConstraints(obj FabricV131Links) error {
	return nil
}
