/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type AccountServiceV1150AccountProviderTypes string

// List of AccountServiceV1150AccountProviderTypes
const (
	ACCOUNTSERVICEV1150ACCOUNTPROVIDERTYPES_REDFISH_SERVICE          AccountServiceV1150AccountProviderTypes = "RedfishService"
	ACCOUNTSERVICEV1150ACCOUNTPROVIDERTYPES_ACTIVE_DIRECTORY_SERVICE AccountServiceV1150AccountProviderTypes = "ActiveDirectoryService"
	ACCOUNTSERVICEV1150ACCOUNTPROVIDERTYPES_LDAP_SERVICE             AccountServiceV1150AccountProviderTypes = "LDAPService"
	ACCOUNTSERVICEV1150ACCOUNTPROVIDERTYPES_OEM                      AccountServiceV1150AccountProviderTypes = "OEM"
	ACCOUNTSERVICEV1150ACCOUNTPROVIDERTYPES_TACAC_SPLUS              AccountServiceV1150AccountProviderTypes = "TACACSplus"
	ACCOUNTSERVICEV1150ACCOUNTPROVIDERTYPES_O_AUTH2                  AccountServiceV1150AccountProviderTypes = "OAuth2"
)

// AssertAccountServiceV1150AccountProviderTypesRequired checks if the required fields are not zero-ed
func AssertAccountServiceV1150AccountProviderTypesRequired(obj AccountServiceV1150AccountProviderTypes) error {
	return nil
}

// AssertAccountServiceV1150AccountProviderTypesConstraints checks if the values respects the defined constraints
func AssertAccountServiceV1150AccountProviderTypesConstraints(obj AccountServiceV1150AccountProviderTypes) error {
	return nil
}
