/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ChassisV1250ThermalDirection string

// List of ChassisV1250ThermalDirection
const (
	CHASSISV1250THERMALDIRECTION_FRONT_TO_BACK ChassisV1250ThermalDirection = "FrontToBack"
	CHASSISV1250THERMALDIRECTION_BACK_TO_FRONT ChassisV1250ThermalDirection = "BackToFront"
	CHASSISV1250THERMALDIRECTION_TOP_EXHAUST   ChassisV1250ThermalDirection = "TopExhaust"
	CHASSISV1250THERMALDIRECTION_SEALED        ChassisV1250ThermalDirection = "Sealed"
)

// AssertChassisV1250ThermalDirectionRequired checks if the required fields are not zero-ed
func AssertChassisV1250ThermalDirectionRequired(obj ChassisV1250ThermalDirection) error {
	return nil
}

// AssertChassisV1250ThermalDirectionConstraints checks if the values respects the defined constraints
func AssertChassisV1250ThermalDirectionConstraints(obj ChassisV1250ThermalDirection) error {
	return nil
}
