/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ConnectionV131DhchapKey - The DHCHAP-specific permission key information for this connection.
type ConnectionV131DhchapKey struct {

	// The local DHCHAP authentication secret.  The value is `null` in responses.
	LocalDHCHAPAuthSecret *string `json:"LocalDHCHAPAuthSecret,omitempty"`

	// The peer DHCHAP authentication secret.  The value is `null` in responses.
	PeerDHCHAPAuthSecret *string `json:"PeerDHCHAPAuthSecret,omitempty"`
}

// AssertConnectionV131DhchapKeyRequired checks if the required fields are not zero-ed
func AssertConnectionV131DhchapKeyRequired(obj ConnectionV131DhchapKey) error {
	return nil
}

// AssertConnectionV131DhchapKeyConstraints checks if the values respects the defined constraints
func AssertConnectionV131DhchapKeyConstraints(obj ConnectionV131DhchapKey) error {
	return nil
}
