/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ResourceV1190PartLocation - The part location for a resource within an enclosure.
type ResourceV1190PartLocation struct {

	// The number that represents the location of the part.  For example, if `LocationType` is `Slot` and this unit is in slot 2, the LocationOrdinalValue is `2`.
	LocationOrdinalValue *int64 `json:"LocationOrdinalValue,omitempty"`

	LocationType *ResourceV1190LocationType `json:"LocationType,omitempty"`

	Orientation *ResourceV1190Orientation `json:"Orientation,omitempty"`

	Reference *ResourceV1190Reference `json:"Reference,omitempty"`

	// The label of the part location, such as a silk-screened name or a printed label.
	ServiceLabel *string `json:"ServiceLabel,omitempty"`
}

// AssertResourceV1190PartLocationRequired checks if the required fields are not zero-ed
func AssertResourceV1190PartLocationRequired(obj ResourceV1190PartLocation) error {
	return nil
}

// AssertResourceV1190PartLocationConstraints checks if the values respects the defined constraints
func AssertResourceV1190PartLocationConstraints(obj ResourceV1190PartLocation) error {
	return nil
}
