/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ResourceV1190RackUnits : The type of rack unit in use.
type ResourceV1190RackUnits string

// List of ResourceV1190RackUnits
const (
	RESOURCEV1190RACKUNITS_OPEN_U  ResourceV1190RackUnits = "OpenU"
	RESOURCEV1190RACKUNITS_EIA_310 ResourceV1190RackUnits = "EIA_310"
)

// AssertResourceV1190RackUnitsRequired checks if the required fields are not zero-ed
func AssertResourceV1190RackUnitsRequired(obj ResourceV1190RackUnits) error {
	return nil
}

// AssertResourceV1190RackUnitsConstraints checks if the values respects the defined constraints
func AssertResourceV1190RackUnitsConstraints(obj ResourceV1190RackUnits) error {
	return nil
}
