/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ResourcePowerState string

// List of ResourcePowerState
const (
	RESOURCEPOWERSTATE_ON           ResourcePowerState = "On"
	RESOURCEPOWERSTATE_OFF          ResourcePowerState = "Off"
	RESOURCEPOWERSTATE_POWERING_ON  ResourcePowerState = "PoweringOn"
	RESOURCEPOWERSTATE_POWERING_OFF ResourcePowerState = "PoweringOff"
	RESOURCEPOWERSTATE_PAUSED       ResourcePowerState = "Paused"
)

// AssertResourcePowerStateRequired checks if the required fields are not zero-ed
func AssertResourcePowerStateRequired(obj ResourcePowerState) error {
	return nil
}

// AssertResourcePowerStateConstraints checks if the values respects the defined constraints
func AssertResourcePowerStateConstraints(obj ResourcePowerState) error {
	return nil
}
