/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// MemoryDomainV150MemorySet - The interleave sets for a memory chunk.
type MemoryDomainV150MemorySet struct {

	// The set of memory for a particular interleave set.
	MemorySet []OdataV4IdRef `json:"MemorySet,omitempty"`

	// The number of items in a collection.
	MemorySetodataCount int64 `json:"MemorySet@odata.count,omitempty"`
}

// AssertMemoryDomainV150MemorySetRequired checks if the required fields are not zero-ed
func AssertMemoryDomainV150MemorySetRequired(obj MemoryDomainV150MemorySet) error {
	for _, el := range obj.MemorySet {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMemoryDomainV150MemorySetConstraints checks if the values respects the defined constraints
func AssertMemoryDomainV150MemorySetConstraints(obj MemoryDomainV150MemorySet) error {
	return nil
}
