/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ResourceV1190Placement - The placement within the addressed location.
type ResourceV1190Placement struct {

	// Area designation or other additional info.
	AdditionalInfo *string `json:"AdditionalInfo,omitempty"`

	// The name of a rack location within a row.
	Rack *string `json:"Rack,omitempty"`

	// The vertical location of the item, in terms of RackOffsetUnits.
	RackOffset *int64 `json:"RackOffset,omitempty"`

	RackOffsetUnits *ResourceV1190RackUnits `json:"RackOffsetUnits,omitempty"`

	// The name of the row.
	Row *string `json:"Row,omitempty"`
}

// AssertResourceV1190PlacementRequired checks if the required fields are not zero-ed
func AssertResourceV1190PlacementRequired(obj ResourceV1190Placement) error {
	return nil
}

// AssertResourceV1190PlacementConstraints checks if the values respects the defined constraints
func AssertResourceV1190PlacementConstraints(obj ResourceV1190Placement) error {
	return nil
}
