/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ComputerSystemV1220Decommission - This action decommissions a system.
type ComputerSystemV1220Decommission struct {

	// Link to invoke action
	Target string `json:"target,omitempty"`

	// Friendly action name
	Title string `json:"title,omitempty"`
}

// AssertComputerSystemV1220DecommissionRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220DecommissionRequired(obj ComputerSystemV1220Decommission) error {
	return nil
}

// AssertComputerSystemV1220DecommissionConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220DecommissionConstraints(obj ComputerSystemV1220Decommission) error {
	return nil
}
