/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type CxlLogicalDeviceV111CxlSemantic string

// List of CxlLogicalDeviceV111CxlSemantic
const (
	CXLLOGICALDEVICEV111CXLSEMANTIC_CX_LIO    CxlLogicalDeviceV111CxlSemantic = "CXLio"
	CXLLOGICALDEVICEV111CXLSEMANTIC_CX_LCACHE CxlLogicalDeviceV111CxlSemantic = "CXLcache"
	CXLLOGICALDEVICEV111CXLSEMANTIC_CX_LMEM   CxlLogicalDeviceV111CxlSemantic = "CXLmem"
)

// AssertCxlLogicalDeviceV111CxlSemanticRequired checks if the required fields are not zero-ed
func AssertCxlLogicalDeviceV111CxlSemanticRequired(obj CxlLogicalDeviceV111CxlSemantic) error {
	return nil
}

// AssertCxlLogicalDeviceV111CxlSemanticConstraints checks if the values respects the defined constraints
func AssertCxlLogicalDeviceV111CxlSemanticConstraints(obj CxlLogicalDeviceV111CxlSemantic) error {
	return nil
}
