/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// SwitchV192VcsSwitch - Virtual CXL Switch (VCS) properties for a switch.
type SwitchV192VcsSwitch struct {

	// The number of Host Device Memory (HDM) Decoders supported by this switch.
	HDMDecoders int64 `json:"HDMDecoders,omitempty"`
}

// AssertSwitchV192VcsSwitchRequired checks if the required fields are not zero-ed
func AssertSwitchV192VcsSwitchRequired(obj SwitchV192VcsSwitch) error {
	return nil
}

// AssertSwitchV192VcsSwitchConstraints checks if the values respects the defined constraints
func AssertSwitchV192VcsSwitchConstraints(obj SwitchV192VcsSwitch) error {
	return nil
}
