/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ComputerSystemV1220IndicatorLed string

// List of ComputerSystemV1220IndicatorLed
const (
	COMPUTERSYSTEMV1220INDICATORLED_UNKNOWN  ComputerSystemV1220IndicatorLed = "Unknown"
	COMPUTERSYSTEMV1220INDICATORLED_LIT      ComputerSystemV1220IndicatorLed = "Lit"
	COMPUTERSYSTEMV1220INDICATORLED_BLINKING ComputerSystemV1220IndicatorLed = "Blinking"
	COMPUTERSYSTEMV1220INDICATORLED_OFF      ComputerSystemV1220IndicatorLed = "Off"
)

// AssertComputerSystemV1220IndicatorLedRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220IndicatorLedRequired(obj ComputerSystemV1220IndicatorLed) error {
	return nil
}

// AssertComputerSystemV1220IndicatorLedConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220IndicatorLedConstraints(obj ComputerSystemV1220IndicatorLed) error {
	return nil
}
