/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// MemoryDomainV150MemorySet - The interleave sets for a memory chunk.
type MemoryDomainV150MemorySet struct {

	// The set of memory for a particular interleave set.
	MemorySet []OdataV4IdRef `json:"MemorySet,omitempty"`

	// The number of items in a collection.
	MemorySetodataCount int64 `json:"MemorySet@odata.count,omitempty"`
}

// AssertMemoryDomainV150MemorySetRequired checks if the required fields are not zero-ed
func AssertMemoryDomainV150MemorySetRequired(obj MemoryDomainV150MemorySet) error {
	for _, el := range obj.MemorySet {
		if err := AssertOdataV4IdRefRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertMemoryDomainV150MemorySetConstraints checks if the values respects the defined constraints
func AssertMemoryDomainV150MemorySetConstraints(obj MemoryDomainV150MemorySet) error {
	return nil
}
