/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// PortV1110GenZ - This type defines Gen-Z specific port properties.
type PortV1110GenZ struct {
	LPRT OdataV4IdRef `json:"LPRT,omitempty"`

	MPRT OdataV4IdRef `json:"MPRT,omitempty"`

	VCAT OdataV4IdRef `json:"VCAT,omitempty"`
}

// AssertPortV1110GenZRequired checks if the required fields are not zero-ed
func AssertPortV1110GenZRequired(obj PortV1110GenZ) error {
	if err := AssertOdataV4IdRefRequired(obj.LPRT); err != nil {
		return err
	}
	if err := AssertOdataV4IdRefRequired(obj.MPRT); err != nil {
		return err
	}
	if err := AssertOdataV4IdRefRequired(obj.VCAT); err != nil {
		return err
	}
	return nil
}

// AssertPortV1110GenZConstraints checks if the values respects the defined constraints
func AssertPortV1110GenZConstraints(obj PortV1110GenZ) error {
	return nil
}
