/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ConnectionV131Actions - The available actions for this resource.
type ConnectionV131Actions struct {

	// The available OEM-specific actions for this resource.
	Oem map[string]interface{} `json:"Oem,omitempty"`
}

// AssertConnectionV131ActionsRequired checks if the required fields are not zero-ed
func AssertConnectionV131ActionsRequired(obj ConnectionV131Actions) error {
	return nil
}

// AssertConnectionV131ActionsConstraints checks if the values respects the defined constraints
func AssertConnectionV131ActionsConstraints(obj ConnectionV131Actions) error {
	return nil
}
