/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// PortV1110EthernetProperties - Ethernet-specific properties for a port.
type PortV1110EthernetProperties struct {

	// An array of configured MAC addresses that are associated with this network port, including the programmed address of the lowest-numbered network device function, the configured but not active address, if applicable, the address for hardware port teaming, or other network addresses.
	AssociatedMACAddresses []*string `json:"AssociatedMACAddresses,omitempty"`

	// Indicates whether IEEE 802.3az Energy-Efficient Ethernet (EEE) is enabled on this port.
	EEEEnabled *bool `json:"EEEEnabled,omitempty"`

	FlowControlConfiguration PortV1110FlowControl `json:"FlowControlConfiguration,omitempty"`

	FlowControlStatus PortV1110FlowControl `json:"FlowControlStatus,omitempty"`

	// Enable/disable LLDP for this port.
	LLDPEnabled bool `json:"LLDPEnabled,omitempty"`

	LLDPReceive PortV1110LldpReceive `json:"LLDPReceive,omitempty"`

	LLDPTransmit PortV1110LldpTransmit `json:"LLDPTransmit,omitempty"`

	// The set of Ethernet capabilities that this port supports.
	// Deprecated
	SupportedEthernetCapabilities []PortV1110SupportedEthernetCapabilities `json:"SupportedEthernetCapabilities,omitempty"`

	// Indicates whether Wake on LAN (WoL) is enabled on this port.
	WakeOnLANEnabled *bool `json:"WakeOnLANEnabled,omitempty"`
}

// AssertPortV1110EthernetPropertiesRequired checks if the required fields are not zero-ed
func AssertPortV1110EthernetPropertiesRequired(obj PortV1110EthernetProperties) error {
	if err := AssertPortV1110LldpReceiveRequired(obj.LLDPReceive); err != nil {
		return err
	}
	if err := AssertPortV1110LldpTransmitRequired(obj.LLDPTransmit); err != nil {
		return err
	}
	return nil
}

// AssertPortV1110EthernetPropertiesConstraints checks if the values respects the defined constraints
func AssertPortV1110EthernetPropertiesConstraints(obj PortV1110EthernetProperties) error {
	return nil
}
