/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// MemoryV1190Cxl - CXL properties for a memory device.
type MemoryV1190Cxl struct {

	// The size of the label storage area in bytes of this memory device.
	LabelStorageSizeBytes int64 `json:"LabelStorageSizeBytes,omitempty"`

	// Total device non-volatile memory capacity in MiB staged for next activation.  The value is in multiples of 256 MiB.
	StagedNonVolatileSizeMiB int64 `json:"StagedNonVolatileSizeMiB,omitempty"`

	// Total device volatile memory capacity in MiB staged for next activation.  This value is in multiples of 256 MiB.
	StagedVolatileSizeMiB int64 `json:"StagedVolatileSizeMiB,omitempty"`
}

// AssertMemoryV1190CxlRequired checks if the required fields are not zero-ed
func AssertMemoryV1190CxlRequired(obj MemoryV1190Cxl) error {
	return nil
}

// AssertMemoryV1190CxlConstraints checks if the values respects the defined constraints
func AssertMemoryV1190CxlConstraints(obj MemoryV1190Cxl) error {
	return nil
}
