/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type AccountServiceV1150AuthenticationTypes string

// List of AccountServiceV1150AuthenticationTypes
const (
	ACCOUNTSERVICEV1150AUTHENTICATIONTYPES_TOKEN                 AccountServiceV1150AuthenticationTypes = "Token"
	ACCOUNTSERVICEV1150AUTHENTICATIONTYPES_KERBEROS_KEYTAB       AccountServiceV1150AuthenticationTypes = "KerberosKeytab"
	ACCOUNTSERVICEV1150AUTHENTICATIONTYPES_USERNAME_AND_PASSWORD AccountServiceV1150AuthenticationTypes = "UsernameAndPassword"
	ACCOUNTSERVICEV1150AUTHENTICATIONTYPES_OEM                   AccountServiceV1150AuthenticationTypes = "OEM"
)

// AssertAccountServiceV1150AuthenticationTypesRequired checks if the required fields are not zero-ed
func AssertAccountServiceV1150AuthenticationTypesRequired(obj AccountServiceV1150AuthenticationTypes) error {
	return nil
}

// AssertAccountServiceV1150AuthenticationTypesConstraints checks if the values respects the defined constraints
func AssertAccountServiceV1150AuthenticationTypesConstraints(obj AccountServiceV1150AuthenticationTypes) error {
	return nil
}
