/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type PortV1110PortType string

// List of PortV1110PortType
const (
	PORTV1110PORTTYPE_UPSTREAM_PORT      PortV1110PortType = "UpstreamPort"
	PORTV1110PORTTYPE_DOWNSTREAM_PORT    PortV1110PortType = "DownstreamPort"
	PORTV1110PORTTYPE_INTERSWITCH_PORT   PortV1110PortType = "InterswitchPort"
	PORTV1110PORTTYPE_MANAGEMENT_PORT    PortV1110PortType = "ManagementPort"
	PORTV1110PORTTYPE_BIDIRECTIONAL_PORT PortV1110PortType = "BidirectionalPort"
	PORTV1110PORTTYPE_UNCONFIGURED_PORT  PortV1110PortType = "UnconfiguredPort"
)

// AssertPortV1110PortTypeRequired checks if the required fields are not zero-ed
func AssertPortV1110PortTypeRequired(obj PortV1110PortType) error {
	return nil
}

// AssertPortV1110PortTypeConstraints checks if the values respects the defined constraints
func AssertPortV1110PortTypeConstraints(obj PortV1110PortType) error {
	return nil
}
