/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ConnectionV131MemoryRegionInfo - The combination of permissions and memory region information.
type ConnectionV131MemoryRegionInfo struct {

	// Supported I/O access capabilities.
	AccessCapabilities []ConnectionV131AccessCapability `json:"AccessCapabilities,omitempty"`

	AccessState ConnectionV131AccessState `json:"AccessState,omitempty"`

	MemoryRegion OdataV4IdRef `json:"MemoryRegion,omitempty"`
}

// AssertConnectionV131MemoryRegionInfoRequired checks if the required fields are not zero-ed
func AssertConnectionV131MemoryRegionInfoRequired(obj ConnectionV131MemoryRegionInfo) error {
	if err := AssertOdataV4IdRefRequired(obj.MemoryRegion); err != nil {
		return err
	}
	return nil
}

// AssertConnectionV131MemoryRegionInfoConstraints checks if the values respects the defined constraints
func AssertConnectionV131MemoryRegionInfoConstraints(obj ConnectionV131MemoryRegionInfo) error {
	return nil
}
