/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

import (
	"time"
)

// ComputerSystemV1220BootProgress - This object describes the last boot progress state.
type ComputerSystemV1220BootProgress struct {

	// The number of seconds the system spent booting to the operating system during the last boot.
	LastBootTimeSeconds *float32 `json:"LastBootTimeSeconds,omitempty"`

	LastState ComputerSystemV1220BootProgressTypes `json:"LastState,omitempty"`

	// The date and time when the last boot state was updated.
	LastStateTime *time.Time `json:"LastStateTime,omitempty"`

	// The OEM extension.
	Oem map[string]interface{} `json:"Oem,omitempty"`

	// The OEM-specific last state, if the LastState type is `OEM`.
	OemLastState *string `json:"OemLastState,omitempty"`
}

// AssertComputerSystemV1220BootProgressRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220BootProgressRequired(obj ComputerSystemV1220BootProgress) error {
	return nil
}

// AssertComputerSystemV1220BootProgressConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220BootProgressConstraints(obj ComputerSystemV1220BootProgress) error {
	return nil
}
