/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// MemoryV1190FreezeSecurityState - Freezes the security state of the memory device.
type MemoryV1190FreezeSecurityState struct {

	// Link to invoke action
	Target string `json:"target,omitempty"`

	// Friendly action name
	Title string `json:"title,omitempty"`
}

// AssertMemoryV1190FreezeSecurityStateRequired checks if the required fields are not zero-ed
func AssertMemoryV1190FreezeSecurityStateRequired(obj MemoryV1190FreezeSecurityState) error {
	return nil
}

// AssertMemoryV1190FreezeSecurityStateConstraints checks if the values respects the defined constraints
func AssertMemoryV1190FreezeSecurityStateConstraints(obj MemoryV1190FreezeSecurityState) error {
	return nil
}
