/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ComputerSystemV1220GraphicalConnectTypesSupported string

// List of ComputerSystemV1220GraphicalConnectTypesSupported
const (
	COMPUTERSYSTEMV1220GRAPHICALCONNECTTYPESSUPPORTED_KVMIP ComputerSystemV1220GraphicalConnectTypesSupported = "KVMIP"
	COMPUTERSYSTEMV1220GRAPHICALCONNECTTYPESSUPPORTED_OEM   ComputerSystemV1220GraphicalConnectTypesSupported = "OEM"
)

// AssertComputerSystemV1220GraphicalConnectTypesSupportedRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220GraphicalConnectTypesSupportedRequired(obj ComputerSystemV1220GraphicalConnectTypesSupported) error {
	return nil
}

// AssertComputerSystemV1220GraphicalConnectTypesSupportedConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220GraphicalConnectTypesSupportedConstraints(obj ComputerSystemV1220GraphicalConnectTypesSupported) error {
	return nil
}
