/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ComputerSystemV1220BootSourceOverrideMode string

// List of ComputerSystemV1220BootSourceOverrideMode
const (
	COMPUTERSYSTEMV1220BOOTSOURCEOVERRIDEMODE_LEGACY ComputerSystemV1220BootSourceOverrideMode = "Legacy"
	COMPUTERSYSTEMV1220BOOTSOURCEOVERRIDEMODE_UEFI   ComputerSystemV1220BootSourceOverrideMode = "UEFI"
)

// AssertComputerSystemV1220BootSourceOverrideModeRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220BootSourceOverrideModeRequired(obj ComputerSystemV1220BootSourceOverrideMode) error {
	return nil
}

// AssertComputerSystemV1220BootSourceOverrideModeConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220BootSourceOverrideModeConstraints(obj ComputerSystemV1220BootSourceOverrideMode) error {
	return nil
}
