/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ResourceV1190LocationType : The types of locations for a part within an enclosure.
type ResourceV1190LocationType string

// List of ResourceV1190LocationType
const (
	RESOURCEV1190LOCATIONTYPE_SLOT      ResourceV1190LocationType = "Slot"
	RESOURCEV1190LOCATIONTYPE_BAY       ResourceV1190LocationType = "Bay"
	RESOURCEV1190LOCATIONTYPE_CONNECTOR ResourceV1190LocationType = "Connector"
	RESOURCEV1190LOCATIONTYPE_SOCKET    ResourceV1190LocationType = "Socket"
	RESOURCEV1190LOCATIONTYPE_BACKPLANE ResourceV1190LocationType = "Backplane"
	RESOURCEV1190LOCATIONTYPE_EMBEDDED  ResourceV1190LocationType = "Embedded"
)

// AssertResourceV1190LocationTypeRequired checks if the required fields are not zero-ed
func AssertResourceV1190LocationTypeRequired(obj ResourceV1190LocationType) error {
	return nil
}

// AssertResourceV1190LocationTypeConstraints checks if the values respects the defined constraints
func AssertResourceV1190LocationTypeConstraints(obj ResourceV1190LocationType) error {
	return nil
}
