/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type ManagerAccountV1120SnmpEncryptionProtocols string

// List of ManagerAccountV1120SnmpEncryptionProtocols
const (
	MANAGERACCOUNTV1120SNMPENCRYPTIONPROTOCOLS_NONE          ManagerAccountV1120SnmpEncryptionProtocols = "None"
	MANAGERACCOUNTV1120SNMPENCRYPTIONPROTOCOLS_CBC_DES       ManagerAccountV1120SnmpEncryptionProtocols = "CBC_DES"
	MANAGERACCOUNTV1120SNMPENCRYPTIONPROTOCOLS_CFB128_AES128 ManagerAccountV1120SnmpEncryptionProtocols = "CFB128_AES128"
	MANAGERACCOUNTV1120SNMPENCRYPTIONPROTOCOLS_CFB128_AES192 ManagerAccountV1120SnmpEncryptionProtocols = "CFB128_AES192"
	MANAGERACCOUNTV1120SNMPENCRYPTIONPROTOCOLS_CFB128_AES256 ManagerAccountV1120SnmpEncryptionProtocols = "CFB128_AES256"
)

// AssertManagerAccountV1120SnmpEncryptionProtocolsRequired checks if the required fields are not zero-ed
func AssertManagerAccountV1120SnmpEncryptionProtocolsRequired(obj ManagerAccountV1120SnmpEncryptionProtocols) error {
	return nil
}

// AssertManagerAccountV1120SnmpEncryptionProtocolsConstraints checks if the values respects the defined constraints
func AssertManagerAccountV1120SnmpEncryptionProtocolsConstraints(obj ManagerAccountV1120SnmpEncryptionProtocols) error {
	return nil
}
