/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// MemoryV1190ResetToDefaults - The action resets the values of writable properties to factory defaults.
type MemoryV1190ResetToDefaults struct {

	// Link to invoke action
	Target string `json:"target,omitempty"`

	// Friendly action name
	Title string `json:"title,omitempty"`
}

// AssertMemoryV1190ResetToDefaultsRequired checks if the required fields are not zero-ed
func AssertMemoryV1190ResetToDefaultsRequired(obj MemoryV1190ResetToDefaults) error {
	return nil
}

// AssertMemoryV1190ResetToDefaultsConstraints checks if the values respects the defined constraints
func AssertMemoryV1190ResetToDefaultsConstraints(obj MemoryV1190ResetToDefaults) error {
	return nil
}
