/*
 * Composable Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type EndpointV181EntityRole string

// List of EndpointV181EntityRole
const (
	ENDPOINTV181ENTITYROLE_INITIATOR EndpointV181EntityRole = "Initiator"
	ENDPOINTV181ENTITYROLE_TARGET    EndpointV181EntityRole = "Target"
	ENDPOINTV181ENTITYROLE_BOTH      EndpointV181EntityRole = "Both"
)

// AssertEndpointV181EntityRoleRequired checks if the required fields are not zero-ed
func AssertEndpointV181EntityRoleRequired(obj EndpointV181EntityRole) error {
	return nil
}

// AssertEndpointV181EntityRoleConstraints checks if the values respects the defined constraints
func AssertEndpointV181EntityRoleConstraints(obj EndpointV181EntityRole) error {
	return nil
}
