/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type PortV1110MediumType string

// List of PortV1110MediumType
const (
	PORTV1110MEDIUMTYPE_COPPER      PortV1110MediumType = "Copper"
	PORTV1110MEDIUMTYPE_FIBER_OPTIC PortV1110MediumType = "FiberOptic"
)

// AssertPortV1110MediumTypeRequired checks if the required fields are not zero-ed
func AssertPortV1110MediumTypeRequired(obj PortV1110MediumType) error {
	return nil
}

// AssertPortV1110MediumTypeConstraints checks if the values respects the defined constraints
func AssertPortV1110MediumTypeConstraints(obj PortV1110MediumType) error {
	return nil
}
