/*
 * Redfish
 *
 * This contains the definition of a Redfish service.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

type MemoryChunksV161MediaLocation string

// List of MemoryChunksV161MediaLocation
const (
	MEMORYCHUNKSV161MEDIALOCATION_LOCAL  MemoryChunksV161MediaLocation = "Local"
	MEMORYCHUNKSV161MEDIALOCATION_REMOTE MemoryChunksV161MediaLocation = "Remote"
	MEMORYCHUNKSV161MEDIALOCATION_MIXED  MemoryChunksV161MediaLocation = "Mixed"
)

// AssertMemoryChunksV161MediaLocationRequired checks if the required fields are not zero-ed
func AssertMemoryChunksV161MediaLocationRequired(obj MemoryChunksV161MediaLocation) error {
	return nil
}

// AssertMemoryChunksV161MediaLocationConstraints checks if the values respects the defined constraints
func AssertMemoryChunksV161MediaLocationConstraints(obj MemoryChunksV161MediaLocation) error {
	return nil
}
