/*
 * Composer and Fabric Manager Redfish Service OpenAPI
 *
 * This API allows users to interact through the CFM Service with CXL Hosts and Memory Appliances. The main purpose of this interface is to allow the retrieval of information and the creation and mapping of memory from a Memory Appliance to a CXL host.
 *
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package redfishapi

// ComputerSystemV1220HostingRole : The enumerations of HostingRoles specify different features that the hosting ComputerSystem supports.
type ComputerSystemV1220HostingRole string

// List of ComputerSystemV1220HostingRole
const (
	COMPUTERSYSTEMV1220HOSTINGROLE_APPLICATION_SERVER     ComputerSystemV1220HostingRole = "ApplicationServer"
	COMPUTERSYSTEMV1220HOSTINGROLE_STORAGE_SERVER         ComputerSystemV1220HostingRole = "StorageServer"
	COMPUTERSYSTEMV1220HOSTINGROLE_SWITCH                 ComputerSystemV1220HostingRole = "Switch"
	COMPUTERSYSTEMV1220HOSTINGROLE_APPLIANCE              ComputerSystemV1220HostingRole = "Appliance"
	COMPUTERSYSTEMV1220HOSTINGROLE_BARE_METAL_SERVER      ComputerSystemV1220HostingRole = "BareMetalServer"
	COMPUTERSYSTEMV1220HOSTINGROLE_VIRTUAL_MACHINE_SERVER ComputerSystemV1220HostingRole = "VirtualMachineServer"
	COMPUTERSYSTEMV1220HOSTINGROLE_CONTAINER_SERVER       ComputerSystemV1220HostingRole = "ContainerServer"
)

// AssertComputerSystemV1220HostingRoleRequired checks if the required fields are not zero-ed
func AssertComputerSystemV1220HostingRoleRequired(obj ComputerSystemV1220HostingRole) error {
	return nil
}

// AssertComputerSystemV1220HostingRoleConstraints checks if the values respects the defined constraints
func AssertComputerSystemV1220HostingRoleConstraints(obj ComputerSystemV1220HostingRole) error {
	return nil
}
